<?php

namespace App\Http\Requests\Test\Booking;

use Illuminate\Foundation\Http\FormRequest;

class CreateBookingTwoARequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            "actionCode" => "required|string",
            "cabin" => "required|string",
            "airItineraryResBookDesigCode" => "required|string",
            "airItineraryResBookDesigQuantity" => "required|string",
            "airItineraryResBookDesigStatusCode" => "required|string",
            "fareInfoCabin" => "required|string",
            "fareInfoClassCode" => "required|string",
            "fareBaggageAllowanceType" => "required|string",
            "fareBaggageAllowanceMaxAllowedPieces" => "required|string",
            "unitOfMeasureCode" => "required|string",
            "weight" => "required|string",
            "fareGroupName" => "required|string",
            "fareReferenceCode" => "required|string",
            "fareReferenceID" => "required|string",
            "fareReferenceName" => "required|string",
            "fareInfoFlightSegmentSequence" => "required|string",
            "fareInfoPortTax" => "required|string",
            "fareInfoResBookDesigCode" => "required|string",
            "airlineCode" => "required|string",
            "airlineCompanyFullName" => "required|string",
            "arrivalAirportCityLocationCode" => "required|string",
            "arrivalAirportCityLocationName" => "required|string",
            "arrivalAirportCityLocationNameLanguage" => "required|string",
            "arrivalAirportCountryLocationCode" => "required|string",
            "arrivalAirportCountryLocationName" => "required|string",
            "arrivalAirportCountryLocationNameLanguage" => "required|string",
            "arrivalAirportCountryCurrencyCode" => "required|string",
            "arrivalAirportCodeContext" => "required|string",
            "arrivalAirportLanguage" => "required|string",
            "arrivalAirportLocationCode" => "required|string",
            "arrivalAirportLocationName" => "required|string",
            "arrivalAirportTimeZoneInfo" => "required|string",
            "arrivalAirportDateTime" => "required|string",
            "arrivalAirportDateTimeUTC" => "required|string",
            "departureAirportCityLocationCode" => "required|string",
            "departureAirportCityLocationName" => "required|string",
            "departureAirportCityLocationNameLanguage" => "required|string",
            "departureAirportCountryLocationCode" => "required|string",
            "departureAirportCountryLocationName" => "required|string",
            "departureAirportLocationNameLanguage" => "required|string",
            "departureAirportCountryCurrencyCode" => "required|string",
            "departureAirportCodeContext" => "required|string",
            "departureAirportLanguage" => "required|string",
            "departureAirportLocationCode" => "required|string",
            "departureAirportLocationName" => "required|string",
            "departureAirportTimeZoneInfo" => "required|string",
            "departureDateTime" => "required|string",
            "departureDateTimeUTC" => "required|string",
            "flightNumber" => "required|string",
            "flightSegmentID" => "required|string",
            "ondControlled" => "required|boolean",
            "sector" => "required|string",
            "codeShare" => "required|boolean",
            "distance" => "required|string",
            "equipmentAirEquipType" => "required|string",
            "equipmentChangeOfGauge" => "required|boolean",
            "flightNotesDeiCodeOne" => "required|string",
            "flightNotesExplanationOne" => "required|string",
            "flightNotesNoteOne" => "required|string",
            "flightNotesDeiCodeTwo" => "required|string",
            "flightNotesExplanationTwo" => "required|string",
            "flightNotesNoteTwo" => "required|string",
            "flightNotesDeiCodeThree" => "required|string",
            "flightNotesExplanationThree" => "required|string",
            "flightNotesNoteThree" => "required|string",
            "flownMileageQty" => "required|string",
            "iatciFlight" => "required|boolean",
            "journeyDuration" => "required|string",
            "onTimeRate" => "required|string",
            "remark" => "required|string",
            "secureFlightDataRequired" => "required|boolean",
            "stopQuantity" => "required|string",
            "ticketType" => "required|string",
            "airTravelerListGenderOne" => "required|string",
            "airTravelerPassengerTypeCodeOne" => "required|string",
            "airTravelerPersonGivenNameOne" => "required|string",
            "airTravelerSurnameOne" => "required|string",
            "airTravelerBirthDateOne" => "required|string",
            "contactPersonEmailOne" => "required|string",
            "emailShareMarketIndOne" => "required|boolean",
            "contactPersonMarkedForSendingRezInfoOne" => "required|boolean",
            "personNameGivenNameOne" => "required|string",
            "personNameSurnameOne" => "required|string",
            "contactPersonBirthDateOne" => "required|string",
            "phoneNumberAreaCodeOne" => "required|string",
            "phoneNumberCountryCodeOne" => "required|string",
            "phoneNumberMarkedForSendingRezInfoOne" => "required|boolean",
            "phoneNumberSubscriberNumberOne" => "required|string",
            "contactPersonShareMarketIndOne" => "required|boolean",
            "contactPersonSocialSecurityNumberOne" => "required|string",
            "contactPersonShareContactInfoOne" => "required|boolean",
            "contactPersonRequestedSeatCountOne" => "required|string",
            "airTravelerListGenderTwo" => "required|string",
            "airTravelerPassengerTypeCodeTwo" => "required|string",
            "airTravelerPersonGivenNameTwo" => "required|string",
            "airTravelerSurnameTwo" => "required|string",
            "airTravelerBirthDateTwo" => "required|string",
            "contactPersonEmailTwo" => "required|string",
            "contactPersonMarkedForSendingRezInfoTwo" => "required|boolean",
            "contactPersonGivenNameTwo" => "required|string",
            "contactPersonSurnameTwo" => "required|string",
            "phoneNumberAreaCodeTwo" => "required|string",
            "phoneNumberCountryCodeTwo" => "required|string",
            "phoneNumberMarkedForSendingRezInfoTwo" => "required|boolean",
            "phoneNumberSubscriberNumberTwo" => "required|string",
            "contactPersonShareMarketIndTwo" => "required|boolean",
            "contactPersonSocialSecurityNumberTwo" => "required|string",
            "contactPersonShareContactInfoTwo" => "required|boolean",
            "requestedSeatCountTwo" => "required|string",
            "airTravelerListGenderThree" => "required|string",
            "airTravelerListBirthDateThree" => "required|string",
            "passengerTypeCodeThree" => "required|string",
            "personNameGivenNameThree" => "required|string",
            "personNameSurnameThree" => "required|string",
            "contactPersonShareContactInfoThree" => "required|boolean",
            "requestedSeatCountThree" => "required|string",
            "requestPurposeThree" => "required|string",
            "airTravelerSequenceOne" => "required|string",
            "flightSegmentSequenceOne" => "required|string",
            "SSRCodeOne" => "required|string",
            "SSRExplanationOne" => "required|string",
            "ticketedServiceQuantityOne" => "required|string",
            "ticketedStatusOne" => "required|string",  
            "airTravelerSequenceTwo" => "required|string",
            "flightSegmentSequenceTwo" => "required|string",
            "SSRCodeTwo" => "required|string",
            "SSRExplanationTwo" => "required|string",
            "ticketedServiceQuantityTwo" => "required|string",
            "ticketedStatusTwo" => "required|string"
        ];
    }
}
