<?php

namespace App\Http\Requests\Test;

use Illuminate\Foundation\Http\FormRequest;

class GetExtraChargesAndProductMDRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            "bookingClassCabinOne" => "required|string",
            "bookingClassResBookDesigCodeOne" => "required|string",
            "bookingClassResBookDesigQuantityOne" => "required|string", 
            "bookingClassResBookDesigStatusCodeOne" => "required|string",
            "fareInfoCabinOne" => "required|string", 
            "fareInfoCabonClassCodeOne" => "required|string",
            "fareBaggageAllowanceTypeOne" => "required|string", 
            "fareBaggageAllowanceMaxAllowedPiecesOne" => "required|string",
            "unitOfMeasureCodeOne" => "required|string", 
            "weightOne" => "required|string", 
            "fareGroupNameOne" => "required|string", 
            "fareReferenceCodeOne" => "required|string", 
            "fareReferenceIDOne" => "required|string", 
            "fareReferenceNameOne" => "required|string",
            "flightSegmentSequenceOne" => "required|string", 
            "portTaxOne" => "required|string", 
            "resBookDesigCodeOne" => "required|string", 
            "airlineCodeOne" => "required|string", 
            "companyFullNameOne" => "required|string", 
            "arrivalAirportCityLocationCodeOne" => "required|string",
            "arrivalAirportCityLocationNameOne" => "required|string", 
            "arrivalAirportCityLocationNameLanguageOne" => "required|string", 
            "arrivalAirportCountryLocationCodeOne" => "required|string",
            "arrivalAirportCountryLocationNameOne" => "required|string", 
            "arrivalAirportCountryLocationNameLanguageOne" => "required|string", 
            "arrivalAirportCountryCurrencyCodeOne" => "required|string",
            "arrivalAirportCodeContextOne" => "required|string", 
            "arrivalAirportLanguageOne" => "required|string", 
            "arrivalAirportLocationCodeOne" => "required|string", 
            "arrivalAirportLocationNameOne" => "required|string", 
            "arrivalAirportTimeZoneInfoOne" => "required|string",
            "arrivalDateTimeOne" => "required|string", 
            "arrivalDateTimeUTCOne" => "required|string", 
            "departureAirportCityLocationCodeOne" => "required|string", 
            "departureAirportCityLocationNameOne" => "required|string",
            "departureAirportCityLocationNameLanguageOne" => "required|string", 
            "departureAirportCountryLocationCodeOne" => "required|string", 
            "departureAirportCountryLocationNameOne" => "required|string",
            "departureAirportCountryLocationNameLanguageOne" => "required|string", 
            "departureAirportCountryCurrencyCodeOne" => "required|string", 
            "departureAirportCodeContextOne" => "required|string",
            "departureAirportLanguageOne" => "required|string", 
            "departureAirportLocationCodeOne" => "required|string", 
            "departureAirportLocationNameOne" => "required|string", 
            "departureAirportTimeZoneInfoOne" => "required|string",
            "departureDateTimeOne" => "required|string", 
            "departureDateTimeUTCOne" => "required|string", 
            "flightNumberOne" => "required|string", 
            "flightSegmentIDOne" => "required|string", 
            "ondControlledOne" => "required|boolean", 
            "sectorOne" => "required|string", 
            "codeShareOne" => "required|boolean",
            "distanceOne" => "required|string", 
            "equipmentAirEquipTypeOne" => "required|string", 
            "equipmentChangeOfGaugeOne" => "required|boolean", 
            "flightNotesDeiCodeOne" => "required|string", 
            "flightNotesExplanationOne" => "required|string",
            "flightNotesNoteOne" => "required|string", 
            "flightNotesDeiCodeTwo" => "required|string", 
            "flightNotesExplanationTwo" => "required|string", 
            "flightNotesNoteTwo" => "required|string",
            "flightNotesDeiCodeThree" => "required|string", 
            "flightNotesExplanationThree" => "required|string", 
            "flightNotesNoteThree" => "required|string", 
            "flownMileageQtyOne" => "required|string", 
            "iatciFlightOne" => "required|boolean",
            "journeyDurationOne" => "required|string", 
            "onTimeRateOne" => "required|string", 
            "remarkOne" => "required|string", 
            "secureFlightDataRequiredOne" => "required|boolean", 
            "stopQuantityOne" => "required|string", 
            "ticketTypeOne" => "required|string",          
            "bookingClassCabinTwo" => "required|string",
            "bookingClassResBookDesigCodeTwo" => "required|string",
            "bookingClassResBookDesigQuantityTwo" => "required|string", 
            "bookingClassResBookDesigStatusCodeTwo" => "required|string",
            "fareInfoCabinTwo" => "required|string", 
            "fareInfoCabonClassCodeTwo" => "required|string",
            "fareBaggageAllowanceTypeTwo" => "required|string", 
            "fareBaggageAllowanceMaxAllowedPiecesTwo" => "required|string",
            "unitOfMeasureCodeTwo" => "required|string", 
            "weightTwo" => "required|string", 
            "fareGroupNameTwo" => "required|string", 
            "fareReferenceCodeTwo" => "required|string", 
            "fareReferenceIDTwo" => "required|string", 
            "fareReferenceNameTwo" => "required|string",
            "flightSegmentSequenceTwo" => "required|string", 
            "portTaxTwo" => "required|string", 
            "resBookDesigCodeTwo" => "required|string",
            "airlineCodeTwo" => "required|string", 
            "companyFullNameTwo" => "required|string", 
            "arrivalAirportCityLocationCodeTwo" => "required|string",
            "arrivalAirportCityLocationNameTwo" => "required|string", 
            "arrivalAirportCityLocationNameLanguageTwo" => "required|string", 
            "arrivalAirportCountryLocationCodeTwo" => "required|string",
            "arrivalAirportCountryLocationNameTwo" => "required|string", 
            "arrivalAirportCountryLocationNameLanguageTwo" => "required|string", 
            "arrivalAirportCountryCurrencyCodeTwo" => "required|string",
            "arrivalAirportCodeContextTwo" => "required|string", 
            "arrivalAirportLanguageTwo" => "required|string", 
            "arrivalAirportLocationCodeTwo" => "required|string", 
            "arrivalAirportLocationNameTwo" => "required|string", 
            "arrivalAirportTimeZoneInfoTwo" => "required|string",
            "arrivalDateTimeTwo" => "required|string", 
            "arrivalDateTimeUTCTwo" => "required|string", 
            "departureAirportCityLocationCodeTwo" => "required|string", 
            "departureAirportCityLocationNameTwo" => "required|string",
            "departureAirportCityLocationNameLanguageTwo" => "required|string", 
            "departureAirportCountryLocationCodeTwo" => "required|string", 
            "departureAirportCountryLocationNameTwo" => "required|string",
            "departureAirportCountryLocationNameLanguageTwo" => "required|string", 
            "departureAirportCountryCurrencyCodeTwo" => "required|string", 
            "departureAirportCodeContextTwo" => "required|string",
            "departureAirportLanguageTwo" => "required|string", 
            "departureAirportLocationCodeTwo" => "required|string", 
            "departureAirportLocationNameTwo" => "required|string", 
            "departureAirportTimeZoneInfoTwo" => "required|string",
            "departureDateTimeTwo" => "required|string", 
            "departureDateTimeUTCTwo" => "required|string",
            "flightNumberTwo" => "required|string", 
            "flightSegmentIDTwo" => "required|string", 
            "ondControlledTwo" => "required|boolean", 
            "sectorTwo" => "required|string", 
            "codeShareTwo" => "required|boolean",
            "distanceTwo" => "required|string", 
            "equipmentAirEquipTypeTwo" => "required|string", 
            "equipmentChangeOfGaugeTwo" => "required|boolean", 
            "flightNotesDeiCodeFour" => "required|string", 
            "flightNotesExplanationFour" => "required|string",
            "flightNotesNoteFour" => "required|string", 
            "flightNotesDeiCodeFive" => "required|string", 
            "flightNotesExplanationFive" => "required|string", 
            "flightNotesNoteFive" => "required|string",
            "flightNotesDeiCodeSix" => "required|string", 
            "flightNotesExplanationSix" => "required|string", 
            "flightNotesNoteSix" => "required|string", 
            "flownMileageQtyTwo" => "required|string", 
            "iatciFlightTwo" => "required|boolean",
            "journeyDurationTwo" => "required|string", 
            "onTimeRateTwo" => "required|string", 
            "remarkTwo" => "required|string", 
            "secureFlightDataRequiredTwo" => "required|boolean", 
            "stopQuantityTwo" => "required|string", 
            "ticketTypeTwo" => "required|string",
            "locationCode" => "required|string",
            "passengerTypeCode" => "required|string",
            "passengerTypeQuantity" => "required|string",
            "tripType" => "required|string"
        ];
    }
}
